module.exports = {
    DATABASE:process.env.DATABASE,
    USER:process.env.USER,
    PASSWORD:process.env.PASSWORD,
    DIALECT:process.env.DIALECT,
    HOST:process.env.HOST,
    JWT_ACCESS_TOKEN_SECRET:process.env.JWT_ACCESS_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_SECRET:process.env.JWT_REFRESH_TOKEN_SECRET,
    JWT_ACCESS_TOKEN_EXPIRES_IN:process.env.JWT_ACCESS_TOKEN_EXPIRES_IN,
    JWT_REFRESH_TOKEN_EXPIRES_IN:process.env.JWT_REFRESH_TOKEN_EXPIRES_IN
}
